## Análise Exploratória de Dados (EDA)

Fazemos a primeira análise sobre os dados coletados na Base do INEP

In [7]:
import pandas as pd
from pathlib import Path

In [ ]:
caminho_resultados_2024 = '/home/guilherme-buosi/enem_pipeline/data/raw/2024/RESULTADOS_2024.csv'

resultados_2024 = pd.read_csv(caminho_resultados_2024, encoding="latin-1", sep=";", nrows=100)

,NU_SEQUENCIAL,NU_ANO,CO_ESCOLA,CO_MUNICIPIO_ESC,NO_MUNICIPIO_ESC,CO_UF_ESC,SG_UF_ESC,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,TP_SIT_FUNC_ESC,...,TX_GABARITO_CH,TX_GABARITO_LC,TX_GABARITO_MT,TP_STATUS_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO
0,206403,2024,23052929.0,2301406.0,Aratuba,23.0,CE,2.0,1.0,1.0,...,CECEBEBCDBADDEBBABCDCAECEDADBAEABEADCEDADACBC,CAAAECDDDAECBECEDDCBDEDDCECBDCBCEADBBDBDDCBEDA...,CECEBEDADCAADECDBBCEBDCCCACABBABBADDDCEADBBCE,1.0,80.0,60.0,60.0,80.0,20.0,300.0
1,3604651,2024,42103770.0,4218004.0,Tijucas,42.0,SC,4.0,1.0,1.0,...,DADABCDCECEDEBBBEBCDBADACBCADCEBEADBAECAECEDA,AACEADDDACDADECBBDBEEBDDECCBEDDCADBBDEBCEBDCEC...,DBCECEACADABBECBEDADCCDCCABBBCECEBCEADABBADDD,1.0,160.0,200.0,200.0,180.0,180.0,920.0
2,1461268,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,CAEDBADBEBCCEDADBAEACBCADCEDEBBEBACECEABCDDAD,EAAACDDCDADDCBDEECEECBDCDADEEBCBEBADBCEBDBDDDD...,ABBABBADDDBBCECEADCEBCCCDBADCBEDAECADACDBCECE,1.0,120.0,120.0,40.0,120.0,80.0,480.0
3,4301058,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,ACBCADCEDBAECEDADBADBEBCDADABCDEABCAEDEBBCECE,AACEADACDDCBEDADEEBDDBDBBCEECBDCBADDDCBDEDDCEC...,CEBCEADBBCEADDDABBABBCCDCCECEDBACADECABEDADCB,1.0,140.0,200.0,160.0,160.0,80.0,740.0
4,3148322,2024,21150354.0,2100436.0,Alto Alegre do Maranhão,21.0,MA,2.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1035588,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,3587454,2024,15585689.0,1501402.0,Belém,15.0,PA,4.0,1.0,1.0,...,NaN,NaN,CECEBEDADCAADECDBBCEBDCCCACABBABBADDDCEADBBCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,140768,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,CAEDBADBEBCCEDADBAEACBCADCEDEBBEBACECEABCDDAD,EAAACDDCDADDCBDEECEECBDCDADEEBCBEBADBCEBDBDDDD...,ABBABBADDDBBCECEADCEBCCCDBADCBEDAECADACDBCECE,1.0,100.0,80.0,60.0,120.0,0.0,360.0
8,3541867,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,3371353,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,CECEBEBCDBADDEBBABCDCAECEDADBAEABEADCEDADACBC,CAAAECDDDAECBECEDDCBDEDDCECBDCBCEADBBDBDDCBEDA...,CECEBEDADCAADECDBBCEBDCCCACABBABBADDDCEADBBCE,1.0,120.0,200.0,120.0,120.0,200.0,760.0

###  Informações contidas no dataset: `resultados_2024`

In [11]:
resultados_2024.head(10)

,NU_SEQUENCIAL,NU_ANO,CO_ESCOLA,CO_MUNICIPIO_ESC,NO_MUNICIPIO_ESC,CO_UF_ESC,SG_UF_ESC,TP_DEPENDENCIA_ADM_ESC,TP_LOCALIZACAO_ESC,TP_SIT_FUNC_ESC,...,TX_GABARITO_CH,TX_GABARITO_LC,TX_GABARITO_MT,TP_STATUS_REDACAO,NU_NOTA_COMP1,NU_NOTA_COMP2,NU_NOTA_COMP3,NU_NOTA_COMP4,NU_NOTA_COMP5,NU_NOTA_REDACAO
0,206403,2024,23052929.0,2301406.0,Aratuba,23.0,CE,2.0,1.0,1.0,...,CECEBEBCDBADDEBBABCDCAECEDADBAEABEADCEDADACBC,CAAAECDDDAECBECEDDCBDEDDCECBDCBCEADBBDBDDCBEDA...,CECEBEDADCAADECDBBCEBDCCCACABBABBADDDCEADBBCE,1.0,80.0,60.0,60.0,80.0,20.0,300.0
1,3604651,2024,42103770.0,4218004.0,Tijucas,42.0,SC,4.0,1.0,1.0,...,DADABCDCECEDEBBBEBCDBADACBCADCEBEADBAECAECEDA,AACEADDDACDADECBBDBEEBDDECCBEDDCADBBDEBCEBDCEC...,DBCECEACADABBECBEDADCCDCCABBBCECEBCEADABBADDD,1.0,160.0,200.0,200.0,180.0,180.0,920.0
2,1461268,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,CAEDBADBEBCCEDADBAEACBCADCEDEBBEBACECEABCDDAD,EAAACDDCDADDCBDEECEECBDCDADEEBCBEBADBCEBDBDDDD...,ABBABBADDDBBCECEADCEBCCCDBADCBEDAECADACDBCECE,1.0,120.0,120.0,40.0,120.0,80.0,480.0
3,4301058,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,ACBCADCEDBAECEDADBADBEBCDADABCDEABCAEDEBBCECE,AACEADACDDCBEDADEEBDDBDBBCEECBDCBADDDCBDEDDCEC...,CEBCEADBBCEADDDABBABBCCDCCECEDBACADECABEDADCB,1.0,140.0,200.0,160.0,160.0,80.0,740.0
4,3148322,2024,21150354.0,2100436.0,Alto Alegre do Maranhão,21.0,MA,2.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1035588,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,3587454,2024,15585689.0,1501402.0,Belém,15.0,PA,4.0,1.0,1.0,...,NaN,NaN,CECEBEDADCAADECDBBCEBDCCCACABBABBADDDCEADBBCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,140768,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,CAEDBADBEBCCEDADBAEACBCADCEDEBBEBACECEABCDDAD,EAAACDDCDADDCBDEECEECBDCDADEEBCBEBADBCEBDBDDDD...,ABBABBADDDBBCECEADCEBCCCDBADCBEDAECADACDBCECE,1.0,100.0,80.0,60.0,120.0,0.0,360.0
8,3541867,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,3371353,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,CECEBEBCDBADDEBBABCDCAECEDADBAEABEADCEDADACBC,CAAAECDDDAECBECEDDCBDEDDCECBDCBCEADBBDBDDCBEDA...,CECEBEDADCAADECDBBCEBDCCCACABBABBADDDCEADBBCE,1.0,120.0,200.0,120.0,120.0,200.0,760.0

In [10]:

resultados_2024.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 42 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   NU_SEQUENCIAL           100 non-null    int64
 1   NU_ANO                  100 non-null    int64
 2   CO_ESCOLA               36 non-null     float64
 3   CO_MUNICIPIO_ESC        36 non-null     float64
 4   NO_MUNICIPIO_ESC        36 non-null     str
 5   CO_UF_ESC               36 non-null     float64
 6   SG_UF_ESC               36 non-null     str
 7   TP_DEPENDENCIA_ADM_ESC  36 non-null     float64
 8   TP_LOCALIZACAO_ESC      36 non-null     float64
 9   TP_SIT_FUNC_ESC         36 non-null     float64
 10  CO_MUNICIPIO_PROVA      100 non-null    int64
 11  NO_MUNICIPIO_PROVA      100 non-null    str
 12  CO_UF_PROVA             100 non-null    int64
 13  SG_UF_PROVA             100 non-null    str
 14  TP_PRESENCA_CN          100 non-null    int64
 15  TP_PRESENCA_CH          100 non-null    int64
 16  TP_PRESENCA_LC          100 non-null    int64
 17  TP_PRESENCA_MT          100 non-null    int64
 18  CO_PROVA_CN             65 non-null     float64
 19  CO_PROVA_CH             71 non-null     float64
 20  CO_PROVA_LC             71 non-null     float64
 21  CO_PROVA_MT             65 non-null     float64
 22  NU_NOTA_CN              65 non-null     float64
 23  NU_NOTA_CH              71 non-null     float64
 24  NU_NOTA_LC              71 non-null     float64
 25  NU_NOTA_MT              65 non-null     float64
 26  TX_RESPOSTAS_CN         65 non-null     str
 27  TX_RESPOSTAS_CH         71 non-null     str
 28  TX_RESPOSTAS_LC         71 non-null     str
 29  TX_RESPOSTAS_MT         65 non-null     str
 30  TP_LINGUA               100 non-null    int64
 31  TX_GABARITO_CN          65 non-null     str
 32  TX_GABARITO_CH          71 non-null     str
 33  TX_GABARITO_LC          71 non-null     str
 34  TX_GABARITO_MT          65 non-null     str
 35  TP_STATUS_REDACAO       71 non-null     float64
 36  NU_NOTA_COMP1           71 non-null     float64
 37  NU_NOTA_COMP2           71 non-null     float64
 38  NU_NOTA_COMP3           71 non-null     float64
 39  NU_NOTA_COMP4           71 non-null     float64
 40  NU_NOTA_COMP5           71 non-null     float64
 41  NU_NOTA_REDACAO         71 non-null     float64
dtypes: float64(21), int64(9), str(12)
memory usage: 32.9 KB